#cloud-config
runcmd:
- echo "$(date)" >> /home/rancher/runcmd-log
bootcmd:
- echo "$(date)" >> /home/rancher/bootcmd-log
rancher:
  services:
    user-volumes:
      volumes:
      - /home:/home
      - /opt:/opt
      - /var/lib/kubelet:/var/lib/kubelet
      - /etc/kubernetes:/etc/kubernetes
